"""mensaje de migración

Revision ID: afb0d144ddcf
Revises: 
Create Date: 2025-08-31 14:03:44.088953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb0d144ddcf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Hospital',
    sa.Column('id_hospital', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('direccion', sa.String(length=60), nullable=False),
    sa.Column('estado', sa.Enum('MANTENIMIENTO', 'CERRADO', 'ABIERTO', name='estadohospital'), nullable=False),
    sa.PrimaryKeyConstraint('id_hospital')
    )
    op.create_table('Medicamento',
    sa.Column('id_medicamento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('presentacion', sa.String(length=100), nullable=False),
    sa.Column('unidad_medida', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_medicamento')
    )
    op.create_table('Rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre_rol')
    )
    op.create_table('Tipo_Novedad',
    sa.Column('id_info', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id_info'),
    sa.UniqueConstraint('descripcion')
    )
    op.create_table('Usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('apellido', sa.String(length=60), nullable=False),
    sa.Column('tipo_documento', sa.Enum('CC', 'TI', 'PAS', 'CE', 'RC', name='tipodocumento'), nullable=False),
    sa.Column('num_documento', sa.String(length=60), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=60), nullable=False),
    sa.Column('genero', sa.Enum('FEMENINO', 'MASCULINO', name='genero'), nullable=False),
    sa.Column('direccion', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', 'PENDIENTE', 'SUSPENDIDO', name='estadousuario'), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['Rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_Usuario_correo'), 'Usuario', ['correo'], unique=True)
    op.create_index(op.f('ix_Usuario_num_documento'), 'Usuario', ['num_documento'], unique=True)
    op.create_table('Error_Tecnico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('fecha', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Familiar',
    sa.Column('id_familiar', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_info', sa.Integer(), nullable=True),
    sa.Column('id_paciente', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('Telefono', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_info'], ['Tipo_Novedad.id_info'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_familiar')
    )
    op.create_table('Horario',
    sa.Column('id_horario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('dia', sa.String(length=20), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['id_medico'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_horario')
    )
    op.create_table('Medicacion',
    sa.Column('id_medicacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('id_medicamento', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ACTIVA', 'COMPLETADA', 'CANCELADA', name='estadomedicacion'), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('dosis', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['id_medicamento'], ['Medicamento.id_medicamento'], ),
    sa.ForeignKeyConstraint(['id_medico'], ['Usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_medicacion')
    )
    op.create_table('Novedad',
    sa.Column('id_novedad', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_admin', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=60), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('src', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_admin'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_novedad')
    )
    op.create_table('medico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=True),
    sa.Column('especialidad', sa.Enum('CARDIOLOGIA', 'PEDIATRIA', 'TRAUMATOLOGIA', 'NEUROLOGIA', name='especialidadmedica'), nullable=True),
    sa.Column('estudios', sa.String(length=100), nullable=True),
    sa.Column('calificacion', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_medico'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Cita',
    sa.Column('id_cita', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=True),
    sa.Column('id_medico', sa.Integer(), nullable=True),
    sa.Column('id_medicacion', sa.Integer(), nullable=True),
    sa.Column('id_hospital', sa.Integer(), nullable=True),
    sa.Column('id_info', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('estado', sa.Enum('PROGRAMADA', 'CANCELADA', 'COMPLETADA', 'PENDIENTE', name='estadocita'), nullable=False),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_hospital'], ['Hospital.id_hospital'], ),
    sa.ForeignKeyConstraint(['id_info'], ['Tipo_Novedad.id_info'], ),
    sa.ForeignKeyConstraint(['id_medicacion'], ['Medicacion.id_medicacion'], ),
    sa.ForeignKeyConstraint(['id_medico'], ['Usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cita')
    )
    op.create_table('Info_Novedad',
    sa.Column('id_info', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_admin', sa.Integer(), nullable=True),
    sa.Column('id_novedad', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=60), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('src', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_admin'], ['Usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_novedad'], ['Novedad.id_novedad'], ),
    sa.PrimaryKeyConstraint('id_info')
    )
    op.create_table('Indicaciones',
    sa.Column('id_indicacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('id_cita', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('estado', sa.Enum('PROGRAMADA', 'CANCELADA', 'COMPLETADA', name='estadoindicacion'), nullable=False),
    sa.Column('observaciones', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['id_cita'], ['Cita.id_cita'], ),
    sa.ForeignKeyConstraint(['id_medico'], ['Usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_indicacion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Indicaciones')
    op.drop_table('Info_Novedad')
    op.drop_table('Cita')
    op.drop_table('medico')
    op.drop_table('Novedad')
    op.drop_table('Medicacion')
    op.drop_table('Horario')
    op.drop_table('Familiar')
    op.drop_table('Error_Tecnico')
    op.drop_index(op.f('ix_Usuario_num_documento'), table_name='Usuario')
    op.drop_index(op.f('ix_Usuario_correo'), table_name='Usuario')
    op.drop_table('Usuario')
    op.drop_table('Tipo_Novedad')
    op.drop_table('Rol')
    op.drop_table('Medicamento')
    op.drop_table('Hospital')
    # ### end Alembic commands ###
